using System;
using System.Collections.Generic;

namespace Fap.Domain.DTOs.Credential
{
    public class CredentialDto
    {
        public Guid Id { get; set; }
        public string CredentialId { get; set; } = null!;
        public string CertificateType { get; set; } = null!;
        public string StudentName { get; set; } = null!;
        public string StudentCode { get; set; } = null!;
        public string? SubjectName { get; set; }
        public string? SemesterName { get; set; }
        public string? RoadmapName { get; set; }
        public DateTime IssuedDate { get; set; }
        public DateTime? CompletionDate { get; set; }
        public decimal? FinalGrade { get; set; }
        public string? LetterGrade { get; set; }
        public string? Classification { get; set; }
        public string Status { get; set; } = null!;
        public string? FileUrl { get; set; }
        public string? ShareableUrl { get; set; }
        public string? VerificationHash { get; set; }
        public int ViewCount { get; set; }
        public bool IsOnBlockchain { get; set; }
        public string? BlockchainTransactionHash { get; set; }
    }

    public class CredentialDetailDto : CredentialDto
    {
        public CertificateTemplateDto Template { get; set; } = null!;
        public string? QRCodeData { get; set; }
        public string? ReviewedByName { get; set; }
        public DateTime? ReviewedAt { get; set; }
        public string? ReviewNotes { get; set; }
        public DateTime? LastViewedAt { get; set; }
        public DateTime CreatedAt { get; set; }
        public string? IPFSHash { get; set; }
        public string? PdfUrl { get; set; }
    }

    public class CredentialShareDto
    {
        public Guid CredentialId { get; set; }
        public string CredentialNumber { get; set; } = null!;
        public string StudentName { get; set; } = null!;
        public string CertificateType { get; set; } = null!;
        public string? SubjectName { get; set; }
        public DateTime IssuedDate { get; set; }
        public string? QRCodeData { get; set; }
        public string ShareableUrl { get; set; } = null!;
        public string VerificationHash { get; set; } = null!;
        public bool CanShare { get; set; }
    }

    public class CredentialRequestDto
    {
        public Guid Id { get; set; }
        public string StudentName { get; set; } = null!;
        public string StudentCode { get; set; } = null!;
        public string CertificateType { get; set; } = null!;
        public string? SubjectName { get; set; }
        public string? SemesterName { get; set; }
        public string? RoadmapName { get; set; }
        public DateTime? CompletionDate { get; set; }
        public decimal? FinalGrade { get; set; }
        public string? LetterGrade { get; set; }
        public string Status { get; set; } = null!;
        public bool IsAutoGenerated { get; set; }
        public DateTime CreatedAt { get; set; }
        public string? StudentNotes { get; set; }
        public string? AdminNotes { get; set; }
    }

    public class CertificateTemplateDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = null!;
        public string TemplateType { get; set; } = null!;
        public string? Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public bool IsSample { get; set; }
        public int Version { get; set; }
        public string? TemplateFileUrl { get; set; }
    }

    public class StudentCredentialSummaryDto
    {
        public int TotalCredentials { get; set; }
        public int SubjectCompletionCount { get; set; }
        // REMOVED: SemesterCompletionCount - No longer supported
        // public int SemesterCompletionCount { get; set; }
        public int RoadmapCompletionCount { get; set; }
        public int PendingRequests { get; set; }
        public List<CredentialDto> RecentCredentials { get; set; } = new();
        public List<CredentialRequestDto> PendingRequestsList { get; set; } = new();
    }

    public class CredentialVerificationDto
    {
        public bool IsValid { get; set; }
        public string? Message { get; set; }
        public CredentialDto? Credential { get; set; }
        public DateTime? VerifiedAt { get; set; }
    }

    public class QRCodeResponse
    {
        public Guid CredentialId { get; set; }
        public string QRCodeData { get; set; } = null!;
        public int Size { get; set; }
        public string? ShareableUrl { get; set; }
    }

    /// <summary>
    /// DTO dành cho Public View - Người ngoài xem chứng chỉ qua QR/Link (Không cần đăng nhập)
    /// </summary>
    public class CertificatePublicDto
    {
        public Guid Id { get; set; }
        public string CredentialNumber { get; set; } = string.Empty;
        public string StudentName { get; set; } = string.Empty;
        public string StudentCode { get; set; } = string.Empty;
        public string CertificateType { get; set; } = string.Empty;
        public string? SubjectName { get; set; }
        public string? SemesterName { get; set; }
        public DateTime IssuedDate { get; set; }
        public DateTime? CompletionDate { get; set; }
        public decimal? FinalGrade { get; set; }
        public string? LetterGrade { get; set; }
        public string? Classification { get; set; }
        
        // Blockchain Info
        public bool IsOnBlockchain { get; set; }
        public string? BlockchainTransactionHash { get; set; }
        public bool IsRevoked { get; set; }
        
        // Sharing Info
        public string PublicUrl { get; set; } = string.Empty;
        public string QrCodeData { get; set; } = string.Empty;
        public string FileUrl { get; set; } = string.Empty;
        
        // Verification Status
        public string VerificationStatus { get; set; } = "Unknown"; // "Verified", "Revoked", "Pending"
        public string? VerificationMessage { get; set; }
        
        public string? TemplateName { get; set; }
    }
}
