using System;
using System.ComponentModel.DataAnnotations;

namespace Fap.Domain.DTOs.Credential
{
    public class RequestCredentialRequest
    {
        [Required, MaxLength(50)]
        public string CertificateType { get; set; } = null!; // "SubjectCompletion", "SemesterCompletion", "RoadmapCompletion", "CurriculumCompletion"

        public Guid? SubjectId { get; set; }
        public Guid? SemesterId { get; set; }
        public Guid? RoadmapId { get; set; }

        [MaxLength(500)]
        public string? Notes { get; set; }
    }

    public class ProcessCredentialRequestRequest
    {
        [Required, MaxLength(20)]
        public string Action { get; set; } = null!; // "Approve", "Reject"

        public Guid? TemplateId { get; set; }

        [MaxLength(500)]
        public string? AdminNotes { get; set; }
    }

    public class CreateCredentialRequest
    {
        [Required]
        public Guid StudentId { get; set; }

        [Required]
        public Guid TemplateId { get; set; }

        [Required, MaxLength(50)]
        public string CertificateType { get; set; } = null!;

        public Guid? SubjectId { get; set; }
        public Guid? SemesterId { get; set; }
        public Guid? RoadmapId { get; set; }

        public DateTime? CompletionDate { get; set; }
        public decimal? FinalGrade { get; set; }

        [MaxLength(10)]
        public string? LetterGrade { get; set; }

        [MaxLength(50)]
        public string? Classification { get; set; }
    }

    public class ReviewCredentialRequest
    {
        [Required, MaxLength(20)]
        public string Action { get; set; } = null!; // "Approve", "Reject"

        [MaxLength(500)]
        public string? ReviewNotes { get; set; }
    }

    public class RevokeCredentialRequest
    {
        [Required, MaxLength(500)]
        public string RevocationReason { get; set; } = null!;
    }

    public class GetCredentialsRequest
    {
        public Guid? StudentId { get; set; }
        public string? CertificateType { get; set; }
        public string? Status { get; set; }
        public DateTime? IssuedFrom { get; set; }
        public DateTime? IssuedTo { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 10;
    }

    public class GetCredentialRequestsRequest
    {
        public string? Status { get; set; }
        public string? CertificateType { get; set; }
        public Guid? StudentId { get; set; }
        public bool? IsAutoGenerated { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 10;
    }

    public class CreateCertificateTemplateRequest
    {
        [Required, MaxLength(100)]
        public string Name { get; set; } = null!;

        [Required, MaxLength(50)]
        public string TemplateType { get; set; } = null!;

        [MaxLength(500)]
        public string? Description { get; set; }

        public string? TemplateContent { get; set; }
        public string? TemplateFileUrl { get; set; }
        public string? HeaderImagePath { get; set; }
        public string? FooterImagePath { get; set; }
        public string? BackgroundImagePath { get; set; }
        public string? LogoImagePath { get; set; }
        public string? SignatureImagePath { get; set; }
        public string? TemplateVariables { get; set; }
        public string? CustomStyles { get; set; }

        [MaxLength(20)]
        public string PageSize { get; set; } = "A4";

        [MaxLength(20)]
        public string Orientation { get; set; } = "Landscape";

        public bool IsDefault { get; set; } = false;
    }

    public class UpdateCertificateTemplateRequest
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? TemplateContent { get; set; }
        public string? TemplateFileUrl { get; set; }
        public string? HeaderImagePath { get; set; }
        public string? FooterImagePath { get; set; }
        public string? BackgroundImagePath { get; set; }
        public string? LogoImagePath { get; set; }
        public string? SignatureImagePath { get; set; }
        public string? TemplateVariables { get; set; }
        public string? CustomStyles { get; set; }
        public string? PageSize { get; set; }
        public string? Orientation { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDefault { get; set; }
    }

    public class VerifyCredentialRequest
    {
        public string? CredentialNumber { get; set; }
        public string? VerificationHash { get; set; }
    }

    public class GenerateQRCodeRequest
    {
        [Required]
        public Guid CredentialId { get; set; }

        public int Size { get; set; } = 300;
    }
}
